version: "3"

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - ./backend:/backend
  mom:
    build:
      dockerfile: Dockerfile.dev
      context: ./rabbitmq
    ports:
      - "15672:15672"
  database:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "test"
    ports:
      - "3308:3306"
