apiVersion: skaffold/v1beta15
kind: Config #This is a config file. :whale:
build:
  local:
    push: false #Whether or not to push directly on changes or not
  artifacts:
    - image: oliverloenning/si-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer: #Look for changes in any of these files and rebuild
          - "**/*.ts"
          - "**/*.tsx"
          - "**/*.js"
          - "**/*.css"
          - "**/*.html"
    - image: oliverloenning/si-backend
      context: backend
      jib: {}
deploy:
  kubectl:
    manifests:
      - k8s/frontend-deployment.yaml
      - k8s/backend-deployment.yaml
