apiVersion: skaffold/v1beta15
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: oliverloenning/si-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - "**/*.ts"
          - "**/*.tsx"
          - "**/*.js"
          - "**/*.css"
          - "**/*.html"
    - image: oliverloenning/si-backend
      context: backend
      jib: {}
deploy:
  kubectl:
    manifests:
      - k8s/frontend-deployment.yaml
      - k8s/backend-deployment.yaml
