FROM openjdk:8

WORKDIR /app

# Need gradle to execute test on travis ci
RUN wget -q https://services.gradle.org/distributions/gradle-5.6.4-bin.zip \
    && unzip gradle-5.6.4-bin.zip -d /opt \
    && rm gradle-5.6.4-bin.zip

ENV GRADLE_HOME /opt/gradle-5.6.4
ENV PATH $PATH:/opt/gradle-5.6.4/bin

COPY . .

CMD ["java", "-server", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-XX:InitialRAMFraction=2", "-XX:MinRAMFraction=2", "-XX:MaxRAMFraction=2", "-XX:+UseG1GC", "-XX:MaxGCPauseMillis=100", "-XX:+UseStringDeduplication", "-jar", "./build/libs/backend-all-0.0.1.jar"]