apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: backend
          image: oliverloenning/si-backend
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_USER
              value: "root"
            - name: DATABASE_PASSWORD
              value: "test"
            - name: MOM_SOCKET_IP
              value: mom-cluster-ip-service
            - name: DATABASE_HOSTNAME
              value: database-cluster-ip-service
