apiVersion: v1
kind: Service
metadata:
  name: mom-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: mom
  ports:
    - port: 4369
      targetPort: 4369
    - port: 5671
      targetPort: 5671
    - port: 5672
      targetPort: 5672
    - port: 25672
      targetPort: 25672
    - port: 15675
      targetPort: 15675
